server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/goods
    username: root
    password: root
  application:
    name: service-provider
mybatis:
  type-aliases-package: com.lening.service.serviceprovider.entity

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

